SET CHARSET UTF8;
SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;

DROP DATABASE IF EXISTS dev_database;
CREATE DATABASE dev_database DEFAULT CHARACTER SET UTF8;

DROP DATABASE IF EXISTS prod_database;
CREATE DATABASE prod_database DEFAULT CHARACTER SET UTF8;
